# Generated by Django 5.2.7 on 2026-02-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
