# Generated by Django 5.2.7 on 2026-02-23 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='base_price',
        ),
    ]
