# Generated by Django 5.2.7 on 2026-03-31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_remove_product_stock_product_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRunningMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('machine_name', models.CharField(max_length=255)),
                ('machine_operator', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_machine_runs', to='production.product')),
            ],
            options={
                'verbose_name': 'Daily Running Machine',
                'verbose_name_plural': 'Daily Running Machines',
                'ordering': ['-production_date', '-id'],
            },
        ),
    ]
