# Generated by Django 3.2.25 on 2026-05-19 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrunningmachine',
            name='crusher_operator',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dailyrunningmachine',
            name='extra_work_employee',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dailyrunningmachine',
            name='machine_not_working',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyrunningmachine',
            name='material_mixer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dailyrunningmachine',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_machine_runs', to='production.product'),
        ),
        migrations.AlterField(
            model_name='dailyrunningmachine',
            name='machine_operator',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
