# Generated by Django 3.2.25 on 2026-06-09 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0010_auto_20260519_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('qty_added', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qty_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qty_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_entries', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_entries', to='production.product')),
            ],
            options={
                'verbose_name': 'Production Entry',
                'verbose_name_plural': 'Production Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
