# Generated by Django 3.2.25 on 2026-06-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_productionitem_shifttemplate_targetlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftproductionlog',
            name='point',
            field=models.IntegerField(choices=[(0, '0 – No Penalty'), (1, '1 – Penalty')], default=1),
        ),
    ]
