# Generated by Django 3.2.25 on 2026-05-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='related_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
