# Generated by Django 3.2.25 on 2026-05-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_add_related_id_to_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Senovka Plastics', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('address', models.TextField(blank=True)),
                ('phone1', models.CharField(blank=True, max_length=30, verbose_name='Phone 1')),
                ('phone2', models.CharField(blank=True, max_length=30, verbose_name='Phone 2')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Company Settings',
            },
        ),
    ]
