# Generated by Django 5.2.7 on 2026-02-23 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='payment_method',
        ),
    ]
