# Generated by Django 3.2.25 on 2026-06-09 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_payment_cheque_status'),
        ('customers', '0004_unify_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill_number', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('transaction_type', models.CharField(choices=[('SALE', 'Sale (Credit)'), ('SALE_CASH', 'Sale (Cash/Cheque)'), ('SALE_PARTIAL', 'Sale (Partial Payment)'), ('PAYMENT_CASH', 'Cash Payment'), ('PAYMENT_CHEQUE', 'Cheque Payment'), ('BALANCE_USED', 'Credit Balance Used'), ('OVERPAYMENT', 'Overpayment Credited'), ('BILL_CANCELLED', 'Bill Cancelled'), ('CHEQUE_BOUNCED', 'Cheque Bounced'), ('CHEQUE_CLEARED', 'Cheque Cleared'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment')], max_length=25)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='billing.bill')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Customer Ledger Entry',
                'verbose_name_plural': 'Customer Ledger Entries',
                'ordering': ['date', 'created_at'],
            },
        ),
    ]
