# Generated by Django 3.2.25 on 2026-05-10 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=255)),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('received_date', models.DateField(default=django.utils.timezone.localdate)),
                ('material_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_type', models.CharField(choices=[('KG', 'KG'), ('G', 'G')], default='KG', max_length=2)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('scale_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('weight_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Material Purchase',
                'verbose_name_plural': 'Material Purchases',
                'ordering': ['-received_date', '-id'],
            },
        ),
    ]
