# Generated by Django 3.2.25 on 2026-05-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cheque_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('CLEARED', 'Cleared'), ('BOUNCED', 'Bounced'), ('HOLD', 'On Hold')], max_length=20, null=True),
        ),
    ]
