# Generated by Django 3.2.25 on 2026-07-01 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customerledger_purchase_offset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0005_payment_nullable_bill_customer_direct'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeldBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('bill_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('bill_discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('items_json', models.TextField()),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_bills', to='customers.customer')),
                ('held_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Held Bill',
                'verbose_name_plural': 'Held Bills',
                'ordering': ['-created_at'],
            },
        ),
    ]
